language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.2
  - DJANGO=1.3.4
  - DJANGO=1.2.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q . --use-mirrors
before_script:
  - mysql -e 'create database sentry;'
  - psql -c 'create database sentry;' -U postgres
script:
  - python runtests.py
notifications:
  email:
    recipients:
      - philipe.rp@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - tests
